# Generated by Django 5.2.6 on 2025-10-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.CharField(max_length=50)),
                ('player_o', models.CharField(max_length=50)),
                ('winner', models.CharField(blank=True, choices=[('X', 'X'), ('O', 'O'), ('D', 'Draw')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
